#!/bin/bash

# SVN Revision Extractor for Unix systems
# Written by Burlex, 2008/02/20

revision=`svn info | grep Revision | cut -d' ' -f2`
echo "// This file was automatically generated by the SVN revision extractor." >> svn_revision.cs
echo "// There is no need to modify it." >> svn_revision.cs
echo "using System;" >> svn_revision.cs
echo "" >> svn_revision.cs
echo "namespace Schumix" >> svn_revision.cs
echo "{" >> svn_revision.cs
echo "	struct SvnRevision" >> svn_revision.cs
echo "	{" >> svn_revision.cs
echo "		public static int BUILD_REVISION = "$revision";" >> svn_revision.cs
echo "		public static string BUILD_HOST = \"`hostname -f`\";" >> svn_revision.cs
echo "		public static string BUILD_USER = \"$USER\";" >> svn_revision.cs
echo "	}" >> svn_revision.cs
echo "}" >> svn_revision.cs
echo "" >> svn_revision.cs
echo $revision;
