/* MySql.sql */

DROP TABLE IF EXISTS
`admins`,
`banned`,
`calendar`,
`channels`,
`gitinfo`,
`hginfo`,
`mantisbt`,
`hlmessage`,
`irc_commands`,
`kicklist`,
`localized_console_command`,
`localized_console_command_help`,
`localized_console_warning`,
`localized_command`,
`localized_command_help`,
`localized_warning`,
`message`,
`modelist`,
`notes`,
`notes_users`,
`schumix`,
`svninfo`,
`sznap`,
`uptime`,
`wordpressinfo`,
`ignore_channels`,
`ignore_nicks`,
`ignore_commands`,
`ignore_irc_commands`,
`maffiagame`,
`ignore_addons`;
