// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.
using System;

namespace Schumix
{
	struct SvnRevision
	{
		public static int BUILD_REVISION = 436;
		public static string BUILD_HOST = "megax";
		public static string BUILD_USER = "megax";
	}
}

