#!/bin/bash

homedir="$HOME/.Schumix"
config_file="$HOME/.Schumix/Configs/Schumix.yml"
config_file_compileraddon="$HOME/.Schumix/Configs/CompilerAddon.yml"
config_dir="$HOME/.Schumix/Configs"
sqlite="$HOME/.Schumix/Schumix.db3"

if [ ! -e $homedir ]; then
	mkdir $homedir
fi

if [ ! -e $config_file ]; then
	if [ ! -e $config_dir ]; then
		mkdir $config_dir
	fi

	cp /usr/share/schumix/Schumix.yml $config_file
fi

if [ ! -e $config_file_compileraddon ]; then
	if [ ! -e $config_dir ]; then
		mkdir $config_dir
	fi

	cp /usr/share/schumix/CompilerAddon.yml $config_file_compileraddon
fi

if [ ! -e $sqlite ]; then
	cp /usr/lib/schumix/Schumix.db3 $sqlite
fi

cp -uR /usr/share/schumix/Sql $homedir
cp -uR /usr/lib/schumix/Addons $homedir
cp -uR /usr/lib/schumix/Scripts $homedir

exec mono "/usr/lib/schumix/Schumix.exe" "--config-dir=$config_dir" "--update-ignore" "$@"
