#!/bin/bash

homedir="$HOME/.Schumix"
config_file="$HOME/.Schumix/Configs/Schumix.yml"
config_dir="$HOME/.Schumix/Configs"
addons="$HOME/.Schumix/Addons"
scripts="$HOME/.Schumix/Scripts"
sqlite="$HOME/.Schumix/Schumix.db3"
sqldir="$HOME/.Schumix/Sql"

if [ ! -e $homedir ]; then
	mkdir $homedir
fi

if [ ! -e $config_file ]; then
	if [ ! -e $config_dir ]; then
		mkdir $config_dir
	fi

	cp /usr/share/schumix/Schumix.yml $config_file
fi

if [ ! -e $sqlite ]; then
	cp /usr/lib/schumix/Schumix.db3 $sqlite
fi

if [ ! -e $sqldir ]; then
	cp /usr/share/schumix/Sql $sqldir
fi

if [ ! -e $addons ]; then
	cp -R /usr/lib/schumix/Addons $addons
fi

if [ -e $addons ]; then
	for file in "/usr/lib/schumix/Addons/*.dll"
	do
		cp -u $file $addons
	done
fi

if [ ! -e $scripts ]; then
	cp -R /usr/lib/schumix/Scripts $scripts
fi

exec mono "/usr/lib/schumix/Schumix.exe" "--config-dir=$config_dir" "$@"
