-- huHU
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "game/start", "Ez nem csatorna! Ne pm-ben írj!\nNincs megadva a játék neve!\nFut már játék!\nNincs ilyen játék!");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "game/start/maffiagame", "{0}: Te már játékban vagy itt: {1}");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/start", "{0}: A játékot {1} indította!\nA játék indításához minimum 4 játékos kell!\nTe egy gyilkos vagy. Célod megölni minden falusit. Csak viselkedj természetesen!\nTe vagy a nyomozó. A te dolgod éjszakánként követni 1-1 embert, hogy megtudd, ki is ő valójában, mielőtt még túl késő lenne. Ha szerencséd van, a falusiak hisznek neked - és talán nem lincselnek meg...\nTe vagy a falu egyetlen orvosa. Éjszakánként megmenhtetsz egy-egy embert a zord haláltól. Ha szerencséd van, talán nem te leszel az első áldozat...\nTe egy teljesen hétköznapi civil vagy. Nincs más dolgod, mint kiválasztani nappal, hogy ki lehet a gyilkos, akit meglincseltek, éjszakánként pedig imádkozni az életedért...\nÚj játék lett indítva! Most mindenki megkapja a szerepét.");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/set", "{0}: Sajnálom de a játék már fut!\n{0}: Nincs megadva az állítandó paraméter!\n{0}: Sajnálom, de csak {1}, a játék indítója állíthat a játék menetén!");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/set/info", "Nincs lynch: bekapcsolva\nNo lynch: kikapcsolva\nNincs rang este: bekapcsolva\nNincs rang este: kikapcsolva");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/set/nolynch", "{0}: Nincs megadva hogy on vagy off legyen-e ez a beállítás!\n{0}: A beállítás módosítva lett.\n{0}: Nem on illetve off kifejezés lett megadva!");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/set/night", "{0}: Nincs megadva az állítandó paraméter!");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/set/night/novoice", "{0}: Nincs megadva hogy on vagy off legyen-e ez a beállítás!\n{0}: A beállítás módosítva lett.\n{0}: Nem on illetve off kifejezés lett megadva!");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/stats", "Új játék indul. Jelenleg {0} játékos van.\nJátékosok: {0}\nA játék állása a következő:\nA következő személyek vannak még életben: {0}\nA következő személyek halottak: {0}");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/join", "{0}: Te már játékban vagy itt: {1}\n{0}: A játék épp most indult. Kérlek ne zavard a játékosokat!\n{0}: A játék már megy. Kérlek ne zavard a játékosokat!\n{0}: Bekerültél a játékba!\n{0}: Már játékban vagy!");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "maffiagame/base/leave", "{0}: Kit akarsz kiléptetni?\n{0}: Nem te indítottad a játékot!\n{0}: Te már nem vagy játékos. Kérlek maradj csendben!\n{0}: Te már nem vagy játékos. Kérlek maradj csendben!\n{0} eltűnt egy különös féreglyukban.\n{0}-nak izgalmas szerepe volt a játékban, mint gyilkos. Remélhetőleg halála izgalmasabb lesz.\n{0}-nak izgalmas szerepe volt a játékban, mint nyomozó. Remélhetőleg halála izgalmasabb lesz.\n{0}-nak izgalmas szerepe volt a játékban, mint orvos. Remélhetőleg halála izgalmasabb lesz.\n{0}-nak unalmas szerepe volt a játékban, mint civil. Remélhetőleg halála izgalmasabb lesz.\n{0}-nak nem volt szerepe még a játékban. Remélhetőleg halála izgalmasabb lesz.\nA játék indítója lelépett. A játékot mostantól bárki írányíthatja!");

-- legvégén lesznek ezek megírva
-- INSERT INTO `localized_warning` (`Language`, `Command`, `Text`) VALUES ("huHU", "", "");

-- enUS
