# Schumix config file (yaml)
Schumix:
    Server:
        Enabled: false
        Host: 127.0.0.1
        Port: 35220
        Password: schumix
    Irc:
        ServerName: Default
        Server: localhost
        Port: 6667
        Ssl: false
        Nickname: Schumix2
        Nickname2: _Schumix2
        NickName3: __Schumix2
        UserName: Schumix2
        UserInfo: Schumix2 IRC Bot
        MasterChannel:
            Name: "#schumix2"
            Password:
        IgnoreChannels:
        IgnoreNames:
        NickServ:
            Enabled: false
            Password: password
        HostServ:
            Enabled: false
            Vhost: false
        Wait:
            MessageSending: 400
        Command:
            Prefix: "$"
        MessageType: Privmsg
    Log:
        FileName: Schumix.log
        LogLevel: 2
        LogDirectory: Logs
        IrcLogDirectory: Channels
        IrcLog: false
    MySql:
        Enabled: false
        Host: localhost
        User: root
        Password: password
        Database: database
        Charset: utf8
    SQLite:
        Enabled: false
        FileName: schumix.db3
    Addon:
        Enabled: true
        Ignore: MantisBTRssAddon,SvnRssAddon,GitRssAddon,HgRssAddon,WordPressRssAddon,TesztAddon
        Directory: Addons
    Scripts:
        Lua: false
        Directory: Scripts
    Localization:
        Locale: enUS
    Update:
        Enabled: false
        Version: stable
        Branch: master
        WebPage: https://github.com/megax/Schumix2
