# Schumix config file (yaml)
Schumix:
    Server:
        Enabled: False
        Host: 127.0.0.1
        Port: 35220
        Password: schumix
    Listener:
        Enabled: False
        Port: 36200
        Password: schumix
    Irc:
        ServerName: Default
        Server: localhost
        Password:  
        Port: 6667
        ModeMask: 8
        Ssl: False
        NickName: Schumix2
        NickName2: _Schumix2
        NickName3: __Schumix2
        UserName: Schumix2
        UserInfo: Schumix2 IRC Bot
        MasterChannel:
            Name: "#schumix2"
            Password:  
        IgnoreChannels:  
        IgnoreNames:  
        NickServ:
            Enabled: False
            Password: password
        HostServ:
            Enabled: False
            Vhost: False
        Wait:
            MessageSending: 400
        Command:
            Prefix: "$"
        MessageType: Privmsg
    Log:
        FileName: Schumix.log
        DateFileName: False
        MaxFileSize: 100
        LogLevel: 2
        LogDirectory: Logs
        IrcLogDirectory: Channels
        IrcLog: False
    MySql:
        Enabled: False
        Host: localhost
        Port: 3306
        User: root
        Password: password
        Database: database
        Charset: utf8
    SQLite:
        Enabled: True
        FileName: Schumix.db3
    Addon:
        Enabled: True
        Ignore: MantisBTRssAddon,SvnRssAddon,GitRssAddon,HgRssAddon,WordPressRssAddon,TestAddon,RssAddon
        Directory: Addons
    Scripts:
        Lua: False
        Python: False
        Directory: Scripts
    Crash:
        Directory: Dumps
    Localization:
        Locale: enUS
    Update:
        Enabled: False
        Version: stable
        Branch: master
        WebPage: https://github.com/Schumix/Schumix2
    Shutdown:
        MaxMemory: 1000
    Flooding:
        Seconds: 4
        NumberOfCommands: 2
    Clean:
        Config: False
        Database: False
    ShortUrl:
        Name:  
        ApiKey:  
