-- huHU
UPDATE `localized_command` SET Text = "3Parancsok: add | remove | info | update | language | password" WHERE Language = 'huHU' AND Command = 'channel';
UPDATE `localized_console_command` SET Text = "Parancsok: add | remove | info | update | language | password" WHERE Language = 'huHU' AND Command = 'channel';
UPDATE `localized_command_help` SET Text = "Channel parancsai: add | remove | info | update | language | password" WHERE Language = 'huHU' AND Command = 'channel';
UPDATE `localized_console_command_help` SET Text = "Channel parancsai: add | remove | info | update | language | password" WHERE Language = 'huHU' AND Command = 'channel';
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/add", "Ilyen csatorna nem létezik!\nMár van megadva jelszó a csatornán!\nJelszó lett beállítva a csatornára, jelszó: {0}");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/remove", "Ilyen csatorna nem létezik!\nNincs a csatornához beállítva jelszó!\nJelszó el lett távolítva a csatornáról.");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/update", "Ilyen csatorna nem létezik!\nNincs a csatornához beállítva jelszó!\nÚj jelszó lett beállítva a csatornára, jelszó: {0}");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/info", "Ilyen csatorna nem létezik!\nA csatornán nincs jelszó.\nA csatornán van jelszó.");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/add", "Ilyen csatorna nem létezik!\nMár van megadva jelszó a csatornán!\nJelszó lett beállítva a csatornára, jelszó: {0}");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/remove", "Ilyen csatorna nem létezik!\nNincs a csatornához beállítva jelszó!\nJelszó el lett távolítva a csatornáról.");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/update", "Ilyen csatorna nem létezik!\nNincs a csatornához beállítva jelszó!\nÚj jelszó lett beállítva a csatornára, jelszó: {0}");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/info", "Ilyen csatorna nem létezik!\nA csatornán nincs jelszó.\nA csatornán van jelszó.");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("huHU", "channel/password", "1", "Lehetõvé teszi a jelszó beállítását a csatornán.\nParancsok: add | remove | update | info");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("huHU", "channel/password/add", "1", "Hozzáadja a jelszót a csatornához.\nHasználata: {0}channel password add <csatorna> <jelszó>");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("huHU", "channel/password/remove", "1", "Eltávolítja a jelszót a csatornáról.\nHasználata: {0}channel password remove <csatorna>");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("huHU", "channel/password/update", "1", "Frissíti a csatorna jelszavát.\nHasználata: {0}channel password update <csatorna> <jelszó>");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("huHU", "channel/password/info", "1", "Kiírja a megadott csatorna jelszavának állapotát.\nHasználata: {0}channel password info <csatorna>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password", "Lehetõvé teszi a jelszó beállítását a csatornán.\nParancsok: add | remove | update | info");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/add", "Hozzáadja a jelszót a csatornához.\nHasználata: channel password add <csatorna> <jelszó>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/remove", "Eltávolítja a jelszót a csatornáról.\nHasználata: channel password remove <csatorna>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/update", "Frissíti a csatorna jelszavát.\nHasználata: channel password update <csatorna> <jelszó>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("huHU", "channel/password/info", "Kiírja a megadott csatorna jelszavának állapotát.\nHasználata: channel password info <csatorna>");

-- enUS
UPDATE `localized_warning` SET Text = "Today is {0}'s name day." WHERE Language = 'enUS' AND Command = 'NameDay';
UPDATE `localized_warning` SET Text = "Message succesfully saved." WHERE Language = 'enUS' AND Command = 'Calendar';
UPDATE `localized_command` SET Text = "3Commands: add | remove | info | update | language | password" WHERE Language = 'enUS' AND Command = 'channel';
UPDATE `localized_console_command` SET Text = "Commands: add | remove | info | update | language | password" WHERE Language = 'enUS' AND Command = 'channel';
UPDATE `localized_command_help` SET Text = "Channel commands: add | remove | info | update | language | password" WHERE Language = 'enUS' AND Command = 'channel';
UPDATE `localized_console_command_help` SET Text = "Channel commands: add | remove | info | update | language | password" WHERE Language = 'enUS' AND Command = 'channel';
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/add", "There is no such a channel!\nPassword is already set on the channel!\nPassword is set on the channel, password: {0}");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/remove", "There is no such a channel!\nThere is no password set on the channel!\npassword deleted from the channel.");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/update", "There is no such a channel!\nThere is no password set on the channel!\nNew password set on the channel, password: {0}");
INSERT INTO `localized_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/info", "There is no such a channel!\nThere is no password set on the channel.\nThere is a password on the channel.");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/add", "There is no such a channel!\nPassword is already set on the channel!\n Password set on channel, password: {0}");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/remove", "There is no such a channel!\nThere is no password set on the channel!\n Password deleted from the channel.");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/update", "There is no such a channel!\nThere is no password set on the channel!\nNew password set on the channel, password: {0}");
INSERT INTO `localized_console_command` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/info", "There is no such a channel!\nThere is no password set on the channel!\nThere is a password on the channel.");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("enUS", "channel/password", "1", "You can set a password on the channel with it.\nCommands: add | remove | update | info");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("enUS", "channel/password/add", "1", "Set password on the channel.\nUse: {0}channel password add <channel> <password>");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("enUS", "channel/password/remove", "1", "Delete password from the channel.\nUse: {0}channel password remove <channel>");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("enUS", "channel/password/update", "1", "Update password on the channel.\nUse: {0}channel password update <channel> <password>");
INSERT INTO `localized_command_help` (`Language`, `Command`, `Rank`, `Text`) VALUES ("enUS", "channel/password/info", "1", "Show the current channel password statement.\nUse: {0}channel password info <channel>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password", "You can set a password on the channel with it.\nCommands: add | remove | update | info");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/add", "Add password to the channel.\nUse: channel password add <channel> <password>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/remove", "Delete passworld from the channel.\nUse: channel password remove <channel>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/update", "Update password on the channel.\nUse: channel password update <channel> <password>");
INSERT INTO `localized_console_command_help` (`Language`, `Command`, `Text`) VALUES ("enUS", "channel/password/info", "Show the current channel password statement.\nUse: channel password info <channel>");