ALTER TABLE `wordpressinfo` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `wordpressinfo` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `svninfo` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `svninfo` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `mantisbt` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `mantisbt` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `hginfo` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `hginfo` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `gitinfo` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `gitinfo` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `calendar` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `calendar` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `banned` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `banned` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `maffiagame` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `maffiagame` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `kicklist` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `kicklist` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `modelist` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `modelist` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `message` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `message` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `notes` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `notes` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `notes_users` ADD COLUMN `ServerId` INT(10) NOT NULL DEFAULT '1' AFTER `Id`;
ALTER TABLE `notes_users` ADD COLUMN `ServerName` varchar(40) NOT NULL default '' AFTER `ServerId`;
ALTER TABLE `admins` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `banned` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `calendar` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `channels` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `gitinfo` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `hginfo` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `mantisbt` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `hlmessage` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `irc_commands` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `kicklist` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `localized_console_command` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `localized_console_command_help` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `localized_console_warning` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `localized_command` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `localized_command_help` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `localized_warning` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `message` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `modelist` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `notes` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `notes_users` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `schumix` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `svninfo` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `wordpressinfo` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `ignore_channels` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `ignore_nicks` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `ignore_commands` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `ignore_irc_commands` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `maffiagame` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `ignore_addons` CHANGE column `Id` `Id` int(10) unsigned NOT NULL auto_increment;
